export interface FeatureFlags {
  ZENROWS_ENABLED: boolean;
  SCRAPINGBEE_ENABLED: boolean;
  SCRAPERAPI_ENABLED: boolean;
  ML_API_ENABLED: boolean;
  AMAZON_API_ENABLED: boolean;
  CIRCUIT_BREAKER_ENABLED: boolean;
  RATE_LIMITER_ENABLED: boolean;
  CACHE_L1_MEMORY_ENABLED: boolean;
  CACHE_L2_FIRESTORE_ENABLED: boolean;
  ANALYTICS_ENABLED: boolean;
  EVENT_BUS_ENABLED: boolean;
}

export const DEFAULT_FEATURE_FLAGS: FeatureFlags = {
  ZENROWS_ENABLED: true,
  SCRAPINGBEE_ENABLED: true,
  SCRAPERAPI_ENABLED: true,
  ML_API_ENABLED: true,
  AMAZON_API_ENABLED: true,
  CIRCUIT_BREAKER_ENABLED: true,
  RATE_LIMITER_ENABLED: true,
  CACHE_L1_MEMORY_ENABLED: true,
  CACHE_L2_FIRESTORE_ENABLED: true,
  ANALYTICS_ENABLED: true,
  EVENT_BUS_ENABLED: true,
};
